name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ سحب الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4️⃣ NDK (متوافق مع أغلب المود منيوهات)
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      # 5️⃣ صلاحية gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 6️⃣ Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # 7️⃣ رفع الـ APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ModMenu-APK
          path: app/build/outputs/apk/debug/*.apk
